apiVersion: v2
name: logging
description: A Helm chart for Kubernetes
type: application
version: 1.0.0

appVersion: "1.0.0"

dependencies:
- name: loki
  version: 6.7.1
  repository: https://grafana.github.io/helm-charts

- name: promtail
  version: 6.16.4
  repository: https://grafana.github.io/helm-charts
