apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: makeline-service
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: app
    server: https://kubernetes.default.svc
  project:  aks
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  source:
    repoURL: https://github.com/AV86github/kubernetes_infra.git
    path: app/makeline-service/dev
    targetRevision: HEAD
