apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ext
  namespace: app
spec:
  ingressClassName: nginx
  rules:
    - host: front.avol4kov.ru
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: store-front
                port:
                  number: 80
